// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: detect/service/v1/detect.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// request data
type DetectTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId  string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	From     string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To       string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Gas      uint64 `protobuf:"varint,4,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice string `protobuf:"bytes,5,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Value    string `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Data     string `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Nonce    uint64 `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Hash     string `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *DetectTxRequest) Reset() {
	*x = DetectTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_detect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectTxRequest) ProtoMessage() {}

func (x *DetectTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_detect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectTxRequest.ProtoReflect.Descriptor instead.
func (*DetectTxRequest) Descriptor() ([]byte, []int) {
	return file_v1_detect_proto_rawDescGZIP(), []int{0}
}

func (x *DetectTxRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *DetectTxRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DetectTxRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *DetectTxRequest) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *DetectTxRequest) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *DetectTxRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DetectTxRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DetectTxRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *DetectTxRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// response data
type RiskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiskType string   `protobuf:"bytes,1,opt,name=risk_type,json=riskType,proto3" json:"risk_type,omitempty"`
	RiskList []string `protobuf:"bytes,2,rep,name=risk_list,json=riskList,proto3" json:"risk_list,omitempty"`
}

func (x *RiskInfo) Reset() {
	*x = RiskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_detect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskInfo) ProtoMessage() {}

func (x *RiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_detect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskInfo.ProtoReflect.Descriptor instead.
func (*RiskInfo) Descriptor() ([]byte, []int) {
	return file_v1_detect_proto_rawDescGZIP(), []int{1}
}

func (x *RiskInfo) GetRiskType() string {
	if x != nil {
		return x.RiskType
	}
	return ""
}

func (x *RiskInfo) GetRiskList() []string {
	if x != nil {
		return x.RiskList
	}
	return nil
}

type DetectTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsIntercept bool        `protobuf:"varint,1,opt,name=is_intercept,json=isIntercept,proto3" json:"is_intercept,omitempty"`
	RiskInfo    []*RiskInfo `protobuf:"bytes,2,rep,name=risk_info,json=riskInfo,proto3" json:"risk_info,omitempty"`
}

func (x *DetectTxResponse) Reset() {
	*x = DetectTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_detect_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectTxResponse) ProtoMessage() {}

func (x *DetectTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_detect_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectTxResponse.ProtoReflect.Descriptor instead.
func (*DetectTxResponse) Descriptor() ([]byte, []int) {
	return file_v1_detect_proto_rawDescGZIP(), []int{2}
}

func (x *DetectTxResponse) GetIsIntercept() bool {
	if x != nil {
		return x.IsIntercept
	}
	return false
}

func (x *DetectTxResponse) GetRiskInfo() []*RiskInfo {
	if x != nil {
		return x.RiskInfo
	}
	return nil
}

var File_v1_detect_proto protoreflect.FileDescriptor

var file_v1_detect_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x22, 0xd3, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x54,
	0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x61, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x61, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x73,
	0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61,
	0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x44, 0x0a, 0x08, 0x52, 0x69,
	0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x69, 0x73, 0x6b, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x69, 0x73, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x69, 0x73, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x69, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x6f, 0x0a, 0x10, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x63, 0x65, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x69, 0x73, 0x6b, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x32, 0x5f, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12, 0x55, 0x0a, 0x08, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x54, 0x78, 0x12, 0x22, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x3a, 0x0a, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1f, 0x67,
	0x6f, 0x70, 0x6c, 0x75, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_detect_proto_rawDescOnce sync.Once
	file_v1_detect_proto_rawDescData = file_v1_detect_proto_rawDesc
)

func file_v1_detect_proto_rawDescGZIP() []byte {
	file_v1_detect_proto_rawDescOnce.Do(func() {
		file_v1_detect_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_detect_proto_rawDescData)
	})
	return file_v1_detect_proto_rawDescData
}

var file_v1_detect_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_detect_proto_goTypes = []interface{}{
	(*DetectTxRequest)(nil),  // 0: detect.service.v1.DetectTxRequest
	(*RiskInfo)(nil),         // 1: detect.service.v1.RiskInfo
	(*DetectTxResponse)(nil), // 2: detect.service.v1.DetectTxResponse
}
var file_v1_detect_proto_depIdxs = []int32{
	1, // 0: detect.service.v1.DetectTxResponse.risk_info:type_name -> detect.service.v1.RiskInfo
	0, // 1: detect.service.v1.Detect.DetectTx:input_type -> detect.service.v1.DetectTxRequest
	2, // 2: detect.service.v1.Detect.DetectTx:output_type -> detect.service.v1.DetectTxResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_detect_proto_init() }
func file_v1_detect_proto_init() {
	if File_v1_detect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_detect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_detect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_detect_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_detect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_detect_proto_goTypes,
		DependencyIndexes: file_v1_detect_proto_depIdxs,
		MessageInfos:      file_v1_detect_proto_msgTypes,
	}.Build()
	File_v1_detect_proto = out.File
	file_v1_detect_proto_rawDesc = nil
	file_v1_detect_proto_goTypes = nil
	file_v1_detect_proto_depIdxs = nil
}
